all:
	gcc listen.c -o listen
	gcc send.c -o send
	gcc response.c -o response
	gcc listen_request.c -o listen_request
	gcc discover.c -o discover -lpthread
	gcc listen_message.c -o listen_message
	gcc message_send.c -o message_send
